// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZCPWebServices.Data;

namespace ZCPWebServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ejecutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idZcp")
                        .HasColumnType("int");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketCcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paradaReloj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resumenCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcategoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Custom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.BaseZcp", b =>
                {
                    b.Property<string>("idSede")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asignacionEc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asignacionInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asignacionOperacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("banda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clasificacionHechosEstudioCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clasificacionHechosInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codDaneMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoDaneEe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("codigoDaneSede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comunicadoAprobacionRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conceptoEstudioCampoInterventoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("conceptoInstalacionInterventoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoElectronicoDueFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("correoElectronicoDueInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("daneDepartamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dificultadAccesoDda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dificultadAccesoEcDda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionSede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoRevisionRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoSedeDue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoVisita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estadoVisitaRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaAprobacionEstudioCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaAprobacionInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaAprobacionRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaAprobacionReporteInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaEntregaEstudioCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaEntregaInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaEstudioCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicioOperacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaRevisionRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaVisitaConfirmacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaVisitaInspeccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaVisitaRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idBeneficiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idEjecutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idZcpPropuestaCambioEstudiosDeCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idZcpPropuestaCambioInstalaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idZcpPropuestaTraslado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iniciativa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("interventorRevisionRemota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latitudInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitudInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matriculaTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metaEstudioCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("metaInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreEe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreSede")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prioridadProyectoZcp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("radicadoAprobacionInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("radicadoAprobacionInterventoriaEc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("radicadoAprobacionInterventoriaReporteInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("radicadoEntregaEstudioCampo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("radicadoEntregaInstalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rectorDueInicial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rectorDuefinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("regionProyectoZcp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secretaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subRegionArt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefonoContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoConectividad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoEnergia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoEnergiaEncontrado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoRespaldoInstalado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("velBajadaMbps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("velSubidaMbps")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSede");

                    b.ToTable("BaseZcp");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.Caracterizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("educacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etnia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sedeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caracterizaciones");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.ParadaReloj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaFinFalla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicioFalla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicioParada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motivoParadaReloj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketCcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sedeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiempoParadaReloj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParadaReloj");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpire")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.Visita", b =>
                {
                    b.Property<string>("sedeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("descripcionHechosVerificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entidadResponsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idSede")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("interventorAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resultadoVisita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoVisita")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sedeId");

                    b.HasIndex("idSede");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("ZCPWebServices.Data.ViewModels.CaracterizacionesVM", b =>
                {
                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("educacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("etnia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sedeId")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("CaracterizacionesWS");
                });

            modelBuilder.Entity("ZCPWebServices.Data.ViewModels.ParadasRelojVM", b =>
                {
                    b.Property<string>("categoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaFinFalla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicioFalla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicioParada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motivoParadaReloj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketCcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sedeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcategoria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tiempoParadaReloj")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("ParadasRelojWS");
                });

            modelBuilder.Entity("ZCPWebServices.Data.ViewModels.TicketsVM", b =>
                {
                    b.Property<string>("departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ejecutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fechaInicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idZcp")
                        .HasColumnType("int");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketCcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroTicketProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paradaReloj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resumenCierre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subcategoria")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("TicketsWS");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZCPWebServices.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZCPWebServices.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZCPWebServices.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZCPWebServices.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("ZCPWebServices.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.Visita", b =>
                {
                    b.HasOne("ZCPWebServices.Data.Models.BaseZcp", "BaseZcp")
                        .WithMany("Visitas")
                        .HasForeignKey("idSede");

                    b.Navigation("BaseZcp");
                });

            modelBuilder.Entity("ZCPWebServices.Data.Models.BaseZcp", b =>
                {
                    b.Navigation("Visitas");
                });
#pragma warning restore 612, 618
        }
    }
}
